"""Tabela Seguidor

Revision ID: 1030cc4cab2c
Revises: 56023361a1f0
Create Date: 2022-02-16 15:43:42.086814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1030cc4cab2c'
down_revision = '56023361a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidor',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'seguidor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidor')
    # ### end Alembic commands ###
