"""Tabela Postagem

Revision ID: 56023361a1f0
Revises: b265a37cb95d
Create Date: 2022-02-16 15:37:17.487384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56023361a1f0'
down_revision = 'b265a37cb95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postagem', sa.String(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postagem')
    # ### end Alembic commands ###
